baseurl = "/"
languageCode = "en-uk"
title = "Upton - Herceptin - 2019"
theme = "hello-friend"
copyright = ""
paginate = 5

[params]
  subtitle = ""
  # "light" or "dark"
  defaultTheme = "dark"

[params.logo]
  logoText = "Herceptin 2019"
  # or
  #
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/home"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"

[languages]
  [languages.en]
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"